spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${KKOBAK_DB_HOST}:${KKOBAK_DB_PORT}/${KKOBAK_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul
    username: ${KKOBAK_DB_USERNAME}
    password: ${KKOBAK_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: ${KKOBAK_SECURITY_NAME}
      password: ${KKOBAK_SECURITY_PASSWORD}

jwt:
  secret: ${KKOBAK_JWT_SECRET_KEY}
  issuer: ${KKOBAK_JWT_ISSUER} #kkobak
  expiration: ${KKOBAK_JWT_EXPIRATION}  # 24h

#google:
#  clientId: ${KKOBAK_GOOGLE_CLIENT_ID}